### ISSUE TITLE
Docker not installed in image of VM

### ISSUE THREAD

**Issue by 0xtuytuy** [blockapps/azure-getting-started#1]
Hello,

I have tried to install your VM and run the stratos script but I keep getting the same error over and over again:  

`grep: /home/remi/.docker/config.json: No such file or directory`

I have tried to insall docker on the VM but it does not change anything, what could be done to solve this ?

**Comment by typeofgraphic** [comment]
strato script tries to run but returns the following error: "docker is required to be installed and configured for non-root users:"

assuming it is a related issue, as Docker appears to be missing or not setup (I am new to Docker, so help would be appreciated if i am missing something more obvious here)

**Comment by kishorebhatia** [comment]
@typeofgraphic @tuytuy in both your cases if you're spinning up the Azure VM from the marketplace offer, please make sure that the SSH username is "strato" in the VM create UI.

Refer: https://github.com/blockapps/azure-getting-started#azure-offer-vm-creation

Looks like the deployment probably picked up another user-name (than "strato") and so it's not able to find the shell-script that ideally is available if you're logged in to your Shell as "strato" user (with user's home being: /home/strato)

I suggest that you create a new marketplace VM and use the user-name: "strato" so that should work.
Let us know how it goes. Happy to help!

**Comment by Remi-Tuy** [comment]
I have deleted my old VM and created a new one with the username strato.

I am know not able to login, it keeps telling me the password is not correct...

Why forcing us to use the strato username ? Why not putting the script into the user folder of the user created when the VM is setup ? 

What is the pswd of the strato username that seems to be created automatically ?

**UPDATE**

I have mange to run the script by modifing it to instead of trying to access "~/.docker/config.json" make it access "/home/strato/docker/config.json". This should really be fixed in the script !

It however seems like it was not set proprely...

![capture](https://user-images.githubusercontent.com/30529561/29240523-289c0d98-7f5f-11e7-9c86-0ee05b2266cb.PNG)

**Comment by kishorebhatia** [comment]
@Remi-Tuy Point noted. In some more iterations of this offer: We'll make the script do this internally instead of relying on hard-coded username "strato" 
The "strato" username when set through the VM Creation UI would still need you to explicitly set the SSH password (either that or an SSH key).
<img width="540" alt="screenshot 2017-08-12 09 47 08" src="https://user-images.githubusercontent.com/4626014/29241671-4110276e-7f4c-11e7-93bb-289523ecd728.png">

Also, the "Password is incorrect" could be an issue with Azure SSH password setting when the machine is created. So just reset that and you should be fine.
<img width="939" alt="screenshot 2017-08-12 09 44 31" src="https://user-images.githubusercontent.com/4626014/29241677-52d6794e-7f4c-11e7-92c4-2d3ffd0eabb5.png">

About docker config.json and running our docker containers as $USER in Ubuntu: the username "strato" has been explicitly setup to not require explicit sudo or root permissions while running docker commands e.g. the /var/run/docker.sock file needs permissions for the $USER (in this case "strato") 
So I'd recommend you use this Azure offer with the default "strato" user and your ssh password and the ~/.docker/config.json should be in "strato" user's home already so you don't have to copy.

**Comment by suchitgupta60** [comment]
I had the same issue when setting up with Azure instance. I had to create and delete instances several times to get the right configurations to work. But once you get it right it works like a charm.

Here is what you need to check when you are creating the instance on azure:
1. There are couple different flavor of instances (individual node, single-node, multi-node) that you can pick from. In my case I picked individual node.
2.  Make sure user name of your instance is "strato" and nothing else. Like this:
![screen shot 2017-08-18 at 4 09 17 am](https://user-images.githubusercontent.com/12634462/29450091-4da52da2-83cb-11e7-97bf-fb0132a7659c.png)

Follow this link if you need to setup new key: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys

3. For virtual machine size try and search for F2S Standard with 2 Cores and 4 GB RAM.
4. Assign some static DNS name to your public IP address here like this:
![screen shot 2017-08-18 at 4 17 00 am](https://user-images.githubusercontent.com/12634462/29450294-2881794e-83cc-11e7-8838-aa08e8afb20d.png)

5. In terminal navigate to the folder where your ssh key file is. From that folder run this command ssh strato@example.eastus.cloudapp.azure.com

![screen shot 2017-08-18 at 4 25 14 am](https://user-images.githubusercontent.com/12634462/29450605-493753ec-83cd-11e7-8ae3-9425f46b0494.png)

6. Make sure you add DNS name when starting the script otherwise it will keep showing the Health Network yellow.
![screen shot 2017-08-18 at 4 31 06 am](https://user-images.githubusercontent.com/12634462/29450978-dfe9f014-83ce-11e7-9d58-da7c8d046d4f.png)

Now you should be able to access your strato dashboard at http://example.eastus.cloudapp.azure.com/
with ID: admin and Password: admin

Let me know if this solution works for you. @kishorebhatia you can mark issue as resolved.

**Comment by Remi-Tuy** [comment]
@suchitgupta60 Thanks for the extend response and sorry for answering so late.

Unfortunately it still hasn't worked. I am not sure what could cause this issue.
I have deleted and recreated the VM 5 times with different configurations and the strato username but not success. 

Something I have noticed is when I run  ./strato-run.sh for the first time, I get a bunch of warnings:

`WARNING: The lazyBlocks variable is not set. Defaulting to a blank string.
WARNING: The statsHost variable is not set. Defaulting to a blank string.
WARNING: The evmDebugMode variable is not set. Defaulting to a blank string.
WARNING: The miningThreads variable is not set. Defaulting to a blank string.
WARNING: The redisBDBNumber variable is not set. Defaulting to a blank string.
WARNING: The statsEnable variable is not set. Defaulting to a blank string.
WARNING: The statsPrefix variable is not set. Defaulting to a blank string.
WARNING: The statsSuffix variable is not set. Defaulting to a blank string.
WARNING: The addBootnodes variable is not set. Defaulting to a blank string.
WARNING: The genesis variable is not set. Defaulting to a blank string.
WARNING: The statsFlush variable is not set. Defaulting to a blank string.
WARNING: The useSyncMode variable is not set. Defaulting to a blank string.
WARNING: The backupblocks variable is not set. Defaulting to a blank string.
WARNING: The blockTime variable is not set. Defaulting to a blank string.
WARNING: The bootnode variable is not set. Defaulting to a blank string.
WARNING: The debugFail variable is not set. Defaulting to a blank string.
WARNING: The minBlockDifficulty variable is not set. Defaulting to a blank string.
WARNING: The miningAlgorithm variable is not set. Defaulting to a blank string.
WARNING: The networkID variable is not set. Defaulting to a blank string.
WARNING: The statsPort variable is not set. Defaulting to a blank string.
WARNING: The uiPassword variable is not set. Defaulting to a blank string.
WARNING: The pgpasswd variable is not set. Defaulting to a blank string.
WARNING: The pguser variable is not set. Defaulting to a blank string.
WARNING: The stratourl variable is not set. Defaulting to a blank string.
WARNING: The pghost variable is not set. Defaulting to a blank string.
WARNING: The stateDiffTopic variable is not set. Defaulting to a blank string.
WARNING: The cirrus_zookeeper_conn variable is not set. Defaulting to a blank string.
WARNING: The cirrus_pg_password variable is not set. Defaulting to a blank string.
`
It seems like some global variables are missing or something like that.

**Comment by Remi-Tuy** [comment]
I have just tried again.

It works, but only with certain VM sizes. I have tried with the standard FS2, no problem. I have tried with smaller VMs but the network never starts. 

This is a serious inconvenient, why would the software not even start when smaller VM are used ? And how come no error messages are shown ?

The issue can now be closed

**Comment by kjameslubin** [comment]
Hi @Remi-Tuy - we should discuss the Azure VM size problem separately. If I recall correctly, some of the dependencies in the software (docker, databases, etc.) have minimum memory requirements. I agree that we need much better error messages in those situations. I've put this in our backlog.
